package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0



/**
 * AdminUser generated by hbm2java
 */
public class AdminUser  implements java.io.Serializable {


     private Integer id;
     private User user;

    public AdminUser() {
    }

    public AdminUser(User user) {
       this.user = user;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


