package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int id;
     private String name;
     private Set items = new HashSet(0);

    public Categories() {
    }

	
    public Categories(int id) {
        this.id = id;
    }
    public Categories(int id, String name, Set items) {
       this.id = id;
       this.name = name;
       this.items = items;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


