package com.dal.pojo;
// Generated Mar 22, 2014 10:38:54 AM by Hibernate Tools 3.2.1.GA



/**
 * OrderHistory generated by hbm2java
 */
public class OrderHistory  implements java.io.Serializable {


     private OrderHistoryId id;
     private User user;
     private String description;

    public OrderHistory() {
    }

	
    public OrderHistory(OrderHistoryId id, User user) {
        this.id = id;
        this.user = user;
    }
    public OrderHistory(OrderHistoryId id, User user, String description) {
       this.id = id;
       this.user = user;
       this.description = description;
    }
   
    public OrderHistoryId getId() {
        return this.id;
    }
    
    public void setId(OrderHistoryId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


