package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0



/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart  implements java.io.Serializable {


     private ShoppingCartId id;
     private User user;
     private Item item;
     private Integer quantity;

    public ShoppingCart() {
    }

	
    public ShoppingCart(ShoppingCartId id, User user, Item item) {
        this.id = id;
        this.user = user;
        this.item = item;
    }
    public ShoppingCart(ShoppingCartId id, User user, Item item, Integer quantity) {
       this.id = id;
       this.user = user;
       this.item = item;
       this.quantity = quantity;
    }
   
    public ShoppingCartId getId() {
        return this.id;
    }
    
    public void setId(ShoppingCartId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


