package com.dal.pojo;
// Generated Mar 22, 2014 10:38:54 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Integer balance;
     private String fullName;
     private Date birthdate;
     private String job;
     private String address;
     private String interests;
     private String email;
     private String password;
     private Boolean activeStatus;
     private Boolean loginStatus;
     private Set orderHistories = new HashSet(0);
     private Set shoppingCarts = new HashSet(0);
     private Set adminUsers = new HashSet(0);

    public User() {
    }

    public User(String fullName, Date birthdate, String job, String address, String interests, String email, String password, Boolean activeStatus, Boolean loginStatus, Set orderHistories, Set shoppingCarts, Set adminUsers) {
       this.fullName = fullName;
       this.birthdate = birthdate;
       this.job = job;
       this.address = address;
       this.interests = interests;
       this.email = email;
       this.password = password;
       this.activeStatus = activeStatus;
       this.loginStatus = loginStatus;
       this.orderHistories = orderHistories;
       this.shoppingCarts = shoppingCarts;
       this.adminUsers = adminUsers;
    }

    public Integer getBalance() {
        return balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }
   
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Boolean getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(Boolean loginStatus) {
        this.loginStatus = loginStatus;
    }
    public Set getOrderHistories() {
        return this.orderHistories;
    }
    
    public void setOrderHistories(Set orderHistories) {
        this.orderHistories = orderHistories;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }
    public Set getAdminUsers() {
        return this.adminUsers;
    }
    
    public void setAdminUsers(Set adminUsers) {
        this.adminUsers = adminUsers;
    }




}


