package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private Date birthdate;
     private String job;
     private String address;
     private String interests;
     private Set orderHistories = new HashSet(0);
     private Set shoppingCarts = new HashSet(0);
     private Set adminUsers = new HashSet(0);
     private Set userCredentialses = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, Date birthdate, String job, String address, String interests, Set orderHistories, Set shoppingCarts, Set adminUsers, Set userCredentialses) {
       this.fname = fname;
       this.lname = lname;
       this.birthdate = birthdate;
       this.job = job;
       this.address = address;
       this.interests = interests;
       this.orderHistories = orderHistories;
       this.shoppingCarts = shoppingCarts;
       this.adminUsers = adminUsers;
       this.userCredentialses = userCredentialses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    public Set getOrderHistories() {
        return this.orderHistories;
    }
    
    public void setOrderHistories(Set orderHistories) {
        this.orderHistories = orderHistories;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }
    public Set getAdminUsers() {
        return this.adminUsers;
    }
    
    public void setAdminUsers(Set adminUsers) {
        this.adminUsers = adminUsers;
    }
    public Set getUserCredentialses() {
        return this.userCredentialses;
    }
    
    public void setUserCredentialses(Set userCredentialses) {
        this.userCredentialses = userCredentialses;
    }




}


