package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0



/**
 * UserCredentials generated by hbm2java
 */
public class UserCredentials  implements java.io.Serializable {


     private UserCredentialsId id;
     private User user;
     private Integer password;
     private Integer activateStatus;
     private Integer loginStatus;

    public UserCredentials() {
    }

	
    public UserCredentials(UserCredentialsId id, User user) {
        this.id = id;
        this.user = user;
    }
    public UserCredentials(UserCredentialsId id, User user, Integer password, Integer activateStatus, Integer loginStatus) {
       this.id = id;
       this.user = user;
       this.password = password;
       this.activateStatus = activateStatus;
       this.loginStatus = loginStatus;
    }
   
    public UserCredentialsId getId() {
        return this.id;
    }
    
    public void setId(UserCredentialsId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getPassword() {
        return this.password;
    }
    
    public void setPassword(Integer password) {
        this.password = password;
    }
    public Integer getActivateStatus() {
        return this.activateStatus;
    }
    
    public void setActivateStatus(Integer activateStatus) {
        this.activateStatus = activateStatus;
    }
    public Integer getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(Integer loginStatus) {
        this.loginStatus = loginStatus;
    }




}


