package com.dal.pojo;
// Generated Mar 21, 2014 1:41:05 PM by Hibernate Tools 3.6.0



/**
 * UserCredentialsId generated by hbm2java
 */
public class UserCredentialsId  implements java.io.Serializable {


     private int userId;
     private String email;

    public UserCredentialsId() {
    }

    public UserCredentialsId(int userId, String email) {
       this.userId = userId;
       this.email = email;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserCredentialsId) ) return false;
		 UserCredentialsId castOther = ( UserCredentialsId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         return result;
   }   


}


